### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [alibouhrouche/portable-lua#1]
Dear @alibouhrouche, I'm sorry, but there are no pre-compiled binaries in Releases section.
How to use it then?

**Comment by alibouhrouche** [comment]
There is a pre-release you can try:
https://github.com/alibouhrouche/portable-lua/releases/download/v1.0-alpha/lua.exe

For usage you can just append you lua file to the executable `copy /b lua.exe+main.lua main.exe`.
There is also an undocumented API for including dependencies such as DLLs and other files, which i might document later.

Have fun.
